### ISSUE TITLE
Text::OutputFilter::PRINT needs to return 1 to match perl’s behavior …

### ISSUE THREAD

**Issue by drmuey** [Tux/Text-OutputFilter#1]
Otherwise implicit returns start behaving differently.

`sub foo { print "Hi\n"; } foo () or die "foo() is not true\n";`

To get it working I add this `BEGIN` block:

```
use Text::OutputFilter;

BEGIN {
    my $of_print = \&Text::OutputFilter::PRINT;
    *Text::OutputFilter::PRINT = sub { $of_print->(@_); return 1 };
    }

**Comment by Tux** [comment]
I replaced `print { $fh } … for @lines` with `print { $fh } map { … } @lines`, causing the default print behaviour to work again. 0.21 is on its way to CPAN.
Thanks for the report.
